### ISSUE TITLE
Version with namespace?

### ISSUE THREAD

**Issue by Antarian** [hakre/XMLReaderIterator#9]
Hi,
Is there any version with namespace? Or have you any specific reason to not have namespace?

**Comment by hakre** [comment]
There is no version with namespace, it's in the global namespace.

Do you run into a concrete problem with that or is that more of a theoretic question of you?

**Comment by PeterLabos** [comment]
I was just curious. It's theoretic question.

**Comment by romka** [comment]
Hi,

with support of namespaces it would be possible to install this library via Composer and autoload it into the project. For now it's necessary to include this library to project manually.

**Comment by hakre** [comment]
Closing as "theoretic".

@romka As you were concerned: To the best what we know, Composer autoload worked fine since version 0.1.0. And that it is independent to namespaces and did not require manually inclusion (apart from the standard `vendor/autoload.php`).

You perhaps were looking at the single inclusion file with all classes in one file. It is for the gist-edition, it roots in very early releases (and for php versions unsupported by Composer). We keep it for convenience/project backwards compatibility. If your php version constraints allow it, feel free to install with Composer.
